# Generated by Django 5.1.1 on 2024-09-23 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('left', models.IntegerField()),
                ('right', models.IntegerField()),
                ('level', models.IntegerField()),
                ('active', models.IntegerField(default=1)),
                ('name', models.TextField(max_length=600)),
                ('date_modify', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('teck_id', models.IntegerField(blank=True, null=True)),
                ('teck_name', models.TextField(blank=True, max_length=600, null=True)),
                ('teck_tree', models.TextField(blank=True, max_length=6000, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kategoria',
            },
        ),
    ]
