# Generated by Django 5.1.1 on 2024-09-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
