# Generated by Django 5.1.1 on 2024-09-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categories_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teckdock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_parent', models.IntegerField()),
                ('STR_DES_ID', models.IntegerField()),
                ('left', models.IntegerField()),
                ('right', models.IntegerField()),
                ('level', models.IntegerField()),
                ('leaf', models.IntegerField(default=1)),
                ('type', models.TextField(max_length=600)),
                ('name', models.TextField(max_length=600)),
                ('path', models.TextField(max_length=600)),
                ('date_modify', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Teckdock Kategoria',
            },
        ),
    ]
