# Generated by Django 5.1.1 on 2024-09-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_teckdock'),
    ]

    operations = [
        migrations.AddField(
            model_name='teckdock',
            name='category_name',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='teckdock',
            name='category_path',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
    ]
